# Generated by Django 5.1.7 on 2025-03-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Закладка')),
                ('url_name', models.CharField(max_length=255, unique=True, verbose_name='Имя URL')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Папка в меню')),
                ('category_slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug категории')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('icon_class', models.CharField(help_text="Например: 'fa fa-home' для FontAwesome", max_length=255, verbose_name='Класс иконки')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ['order'],
            },
        ),
    ]
