# Generated by Django 5.1.7 on 2025-11-14 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ledger', 'Бухгалтерия'), ('commerce', 'Продажи'), ('departments', 'Отделы')], max_length=50, unique=True, verbose_name='Название категории')),
                ('display_name', models.CharField(max_length=100, verbose_name='Отображаемое название')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория меню',
                'verbose_name_plural': 'Категории меню',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu.menucategory', verbose_name='Категория'),
        ),
    ]
