# Generated by Django 5.1.7 on 2025-03-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Права, связанные с этим пунктом меню', related_name='menu_items', to='users.permission', verbose_name='Права'),
        ),
    ]
