# Generated by Django 5.1.7 on 2025-04-12 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Пункт меню', 'verbose_name_plural': 'Пункты меню'},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='category_slug',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='order',
        ),
    ]
