# Generated by Django 5.1.7 on 2026-01-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menucategory_menuitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='name',
            field=models.CharField(choices=[('ledger', 'Бухгалтерия'), ('commerce', 'Продажи'), ('departments', 'Отделы'), ('report', 'Отчет')], max_length=50, unique=True, verbose_name='Название категории'),
        ),
    ]
