# Generated by Django 5.1.7 on 2026-02-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menucategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='name',
            field=models.CharField(choices=[('ledger', 'Бухгалтерия'), ('commerce', 'Продажи'), ('departments', 'Отделы'), ('report', 'Отчет'), ('settings', 'Настройки')], max_length=50, unique=True, verbose_name='Название категории'),
        ),
    ]
