# Generated by Django 5.1.7 on 2025-03-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Клиент')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН')),
                ('legal_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Юр. название')),
                ('director', models.CharField(blank=True, max_length=255, null=True, verbose_name='Директор')),
                ('ogrn', models.CharField(blank=True, max_length=13, null=True, verbose_name='ОГРН')),
                ('basis', models.CharField(blank=True, max_length=255, null=True, verbose_name='Основание')),
                ('legal_address', models.TextField(blank=True, null=True, verbose_name='Адрес юридический')),
                ('actual_address', models.TextField(blank=True, null=True, verbose_name='Адрес фактический')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Баланс')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orders/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('size', models.PositiveIntegerField(verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тип файла')),
            ],
            options={
                'verbose_name': 'Тип файла',
                'verbose_name_plural': 'Типы файлов',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма заказа')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Срок сдачи')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Оплачено')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказов',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название типа продукции')),
            ],
            options={
                'verbose_name': 'Продукция',
                'verbose_name_plural': 'Продукция',
            },
        ),
    ]
