# Generated by Django 5.1.7 on 2025-09-23 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название объекта')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='commerce.client')),
            ],
            options={
                'verbose_name': 'Объект клиента',
                'verbose_name_plural': 'Объекты клиентов',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='client_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='commerce.clientobject', verbose_name='Объект клиента'),
        ),
    ]
