# Generated by Django 5.1.7 on 2025-09-23 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_clientobject_order_client_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientobject',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_objects', to='commerce.client'),
        ),
    ]
