# Generated by Django 5.1.7 on 2025-04-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_alter_order_options_remove_order_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Сумма, которая уже была оплачена по данному заказу', max_digits=12, verbose_name='Оплаченная сумма'),
        ),
    ]
