# Generated by Django 5.1.7 on 2025-10-08 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_alter_clientobject_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('phone1', models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон 1')),
                ('phone2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон 2')),
                ('phone3', models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон 3')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='ДР')),
                ('socials', models.TextField(blank=True, null=True, verbose_name='Социалки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='commerce.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Контакт клиента',
                'verbose_name_plural': 'Контакты клиентов',
            },
        ),
    ]
