# Generated by Django 5.1.7 on 2025-06-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_order_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='documents_required',
            field=models.BooleanField(default=False, help_text='Отметьте, если для заказа требуются документы', verbose_name='Док-ты'),
        ),
    ]
