# Generated by Django 5.1.7 on 2025-10-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отправлено в архив'),
        ),
    ]
