# Generated by Django 5.1.7 on 2025-10-09 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_order_archived_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.RemoveField(
            model_name='document',
            name='size',
        ),
        migrations.AddField(
            model_name='document',
            name='file_name',
            field=models.CharField(default='', max_length=255, verbose_name='Имя файла'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Размер файла (байт)'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_url',
            field=models.URLField(blank=True, default='', max_length=1000, verbose_name='Ссылка на документ'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.filetype', verbose_name='Тип файла'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
