# Generated by Django 5.1.7 on 2025-10-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_remove_document_file_remove_document_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_url',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Имя файла'),
        ),
        migrations.AddField(
            model_name='document',
            name='size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Размер файла (в байтах)'),
        ),
        migrations.AddField(
            model_name='document',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL файла'),
        ),
    ]
