# Generated by Django 5.1.7 on 2025-10-09 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_remove_document_file_name_remove_document_file_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='documents',
        ),
        migrations.AddField(
            model_name='document',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='commerce.order', verbose_name='Заказ'),
        ),
    ]
