# Generated by Django 5.1.7 on 2025-11-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_remove_order_documents_document_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='required_documents',
            field=models.BooleanField(default=False, help_text='Документы', verbose_name='Документы'),
        ),
    ]
