# Generated by Django 5.1.7 on 2025-11-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_order_required_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Количество единиц продукции', max_digits=12, null=True, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='order',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена за одну единицу продукции', max_digits=12, null=True, verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма'),
        ),
    ]
