# Generated by Django 5.1.7 on 2025-11-12 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0010_order_quantity_order_unit_price_alter_order_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
    ]
