# Generated by Django 5.1.7 on 2025-11-12 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0011_order_executor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название отдела')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='executor',
        ),
        migrations.CreateModel(
            name='DepartmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название статуса')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='commerce.department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Статус отдела',
                'verbose_name_plural': 'Статусы отделов',
                'ordering': ['department'],
            },
        ),
        migrations.CreateModel(
            name='OrderDepartmentWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, help_text='Когда работа была начата в отделе', null=True, verbose_name='Начало работы')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Когда работа была завершена в отделе', null=True, verbose_name='Окончание работы')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_works', to='commerce.department', verbose_name='Отдел')),
                ('executor', models.ForeignKey(blank=True, help_text='Ответственный исполнитель в отделе', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_works', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_works', to='commerce.order', verbose_name='Заказ')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_works', to='commerce.departmentstatus', verbose_name='Статус работы')),
            ],
            options={
                'verbose_name': 'Работа отдела по заказу',
                'verbose_name_plural': 'Работы отделов по заказам',
                'ordering': ['order', 'department'],
                'unique_together': {('order', 'department')},
            },
        ),
    ]
