# Generated by Django 5.1.7 on 2025-11-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0012_department_remove_order_executor_departmentstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-идентификатор отдела (например: printing, cutting)', max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
