# Generated by Django 5.1.7 on 2025-11-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0013_orderstatus_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='slug',
        ),
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-идентификатор отдела (например: printing, cutting)', max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
