# Generated by Django 5.1.7 on 2025-11-12 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0014_remove_orderstatus_slug_department_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDepartmentWorkMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, help_text='Отметка о прочтении сообщения', verbose_name='Прочитано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('order_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='commerce.orderdepartmentwork', verbose_name='Работа отдела')),
                ('recipient', models.ForeignKey(blank=True, help_text='Конкретный получатель сообщения (если указан)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Сообщение по работе отдела',
                'verbose_name_plural': 'Сообщения по работам отделов',
                'ordering': ['-created'],
            },
        ),
    ]
