# Generated by Django 5.1.7 on 2025-11-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0015_orderdepartmentworkmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Сумма, которая уже была оплачена по данному заказу', max_digits=12, verbose_name='Оплаченная сумма'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Количество единиц продукции', max_digits=12, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Цена за одну единицу продукции', max_digits=12, null=True, verbose_name='Цена за единицу'),
        ),
    ]
