# Generated by Django 5.1.7 on 2025-11-24 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0016_alter_order_amount_alter_order_paid_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderWorkStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название статуса')),
                ('department', models.ForeignKey(blank=True, help_text='Оставьте пустым для общих статусов', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unique_statuses', to='commerce.department', verbose_name='Отдел (если статус уникален для отдела)')),
            ],
            options={
                'verbose_name': 'Статус работы отдела',
                'verbose_name_plural': 'Статусы работ отделов',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='orderdepartmentwork',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_works', to='commerce.orderworkstatus', verbose_name='Статус работы'),
        ),
        migrations.DeleteModel(
            name='DepartmentStatus',
        ),
    ]
