# Generated by Django 5.1.7 on 2025-11-26 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0017_orderworkstatus_alter_orderdepartmentwork_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='viewers',
            field=models.ManyToManyField(blank=True, help_text='Пользователи, которые могут просматривать этот заказ', related_name='viewable_orders', to=settings.AUTH_USER_MODEL, verbose_name='Доп. пользователи с доступом'),
        ),
    ]
