# Generated by Django 5.1.7 on 2025-11-27 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0018_order_viewers'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название столбца')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Столбец Kanban',
                'verbose_name_plural': 'Столбцы Kanban',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='KanbanClientPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в столбце')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_placements', to='commerce.client', verbose_name='Клиент')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='commerce.kanbancolumn', verbose_name='Столбец')),
            ],
            options={
                'verbose_name': 'Клиент на доске',
                'verbose_name_plural': 'Клиенты на доске',
                'ordering': ['order'],
                'unique_together': {('client',)},
            },
        ),
    ]
