# Generated by Django 5.1.7 on 2025-12-09 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0019_kanbancolumn_kanbanclientplacement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.department', verbose_name='Отдел')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.product', verbose_name='Продукция')),
            ],
            options={
                'verbose_name': 'Отдел продукции',
                'verbose_name_plural': 'Отделы продукции',
                'unique_together': {('product', 'department')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='departments',
            field=models.ManyToManyField(related_name='products', through='commerce.ProductDepartment', to='commerce.department', verbose_name='Доступные отделы'),
        ),
    ]
