# Generated by Django 5.1.7 on 2025-12-15 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0020_productdepartment_product_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdepartmentworkmessage',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_work_messages', to='commerce.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderdepartmentworkmessage',
            name='order_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='commerce.orderdepartmentwork', verbose_name='Работа отдела'),
        ),
    ]
