# Generated by Django 5.1.7 on 2025-12-17 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0021_orderdepartmentworkmessage_order_and_more'),
        ('users', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='chief_user_type',
            field=models.ForeignKey(blank=True, help_text='Тип пользователя, который считается главным в отделе', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chief_departments', to='users.usertype', verbose_name='Главный в отделе (тип пользователя)'),
        ),
    ]
