# Generated by Django 5.1.7 on 2025-12-17 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0022_department_chief_user_type'),
        ('users', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='worker_user_type',
            field=models.ForeignKey(blank=True, help_text='Тип пользователя, который считается работником отдела', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_departments', to='users.usertype', verbose_name='Работник отдела (тип пользователя)'),
        ),
    ]
