# Generated by Django 5.1.7 on 2026-01-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0023_department_worker_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
