# Generated by Django 5.1.7 on 2026-02-11 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0024_document_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='Когда была зафиксирована авария', verbose_name='Начало аварии')),
                ('description', models.TextField(blank=True, help_text='Подробное описание аварии', null=True, verbose_name='Описание аварии')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Когда авария была закрыта', null=True, verbose_name='Закрытие аварии')),
                ('order_department_work', models.ForeignKey(help_text='Авария связана с этой работой отдела', on_delete=django.db.models.deletion.CASCADE, related_name='emergencies', to='commerce.orderdepartmentwork', verbose_name='Работа отдела по заказу')),
                ('resolver', models.ForeignKey(blank=True, help_text='Пользователь, назначенный для устранения аварии', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_emergencies', to=settings.AUTH_USER_MODEL, verbose_name='Работник по устранению')),
            ],
            options={
                'verbose_name': 'Авария',
                'verbose_name_plural': 'Аварии',
                'ordering': ['-started_at'],
            },
        ),
    ]
