# Generated by Django 5.1.7 on 2026-03-04 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0025_emergencyincident'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderworkstatus',
            name='is_final',
            field=models.BooleanField(default=False, help_text='Этот статус назначается при закрытии работы отдела', verbose_name='Статус закрытия работы отдела'),
        ),
        migrations.AddField(
            model_name='orderworkstatus',
            name='is_initial',
            field=models.BooleanField(default=False, help_text='Этот статус назначается автоматически при добавлении работы отдела', verbose_name='Автоматический при добавлении отдела'),
        ),
        migrations.AlterField(
            model_name='orderworkstatus',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unique_statuses', to='commerce.department', verbose_name='Отдел'),
        ),
    ]
