# Generated by Django 5.1.7 on 2026-03-06 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0026_orderworkstatus_is_final_orderworkstatus_is_initial_and_more'),
        ('users', '0009_usertypemenuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetype',
            name='user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usertype', verbose_name='Тип пользователя'),
        ),
    ]
