# Generated by Django 5.1.7 on 2026-03-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0027_filetype_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название основного средства')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Основное средство',
                'verbose_name_plural': 'Основные средства',
            },
        ),
    ]
