# Generated by Django 5.1.7 on 2026-03-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0028_fixedasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название задолженности')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Кредиторская задолженность',
                'verbose_name_plural': 'Кредиторские задолженности',
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название бонуса')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Бонус',
                'verbose_name_plural': 'Бонусы',
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название кредита')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Кредит',
                'verbose_name_plural': 'Кредиты',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Товарный остаток',
                'verbose_name_plural': 'Товарные остатки',
            },
        ),
        migrations.CreateModel(
            name='ShortTermLiability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название обязательства')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Краткосрочное обязательство',
                'verbose_name_plural': 'Краткосрочные обязательства',
            },
        ),
    ]
