# Generated by Django 5.1.7 on 2026-05-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0031_alter_accountspayable_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="url",
            field=models.CharField(blank=True, max_length=1024, verbose_name="URL файла"),
        ),
    ]
