# Generated by Django 5.1.7 on 2026-05-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0033_manager_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='managernote',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время выполнения'),
        ),
        migrations.AlterModelOptions(
            name='managernote',
            options={
                'ordering': ['date', 'scheduled_time', 'id'],
                'verbose_name': 'Заметка менеджера',
                'verbose_name_plural': 'Заметки менеджеров',
            },
        ),
    ]