# Generated by Django 5.1.7 on 2026-05-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0034_managernote_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='managernote',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Напоминание отправлено'),
        ),
    ]