# Generated by Django 5.1.7 on 2026-06-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0037_alter_order_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdepartmentwork',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Активна ли работа отдела по заказу (переключается кнопками старт/стоп)', verbose_name='Активна'),
        ),
    ]
