# Generated by Django 5.1.7 on 2026-06-17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0038_orderdepartmentwork_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdepartmentwork',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name='Создано',
            ),
            preserve_default=False,
        ),
    ]
