# Generated by Django 5.1.7 on 2026-06-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0039_orderdepartmentwork_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
