# Generated by Django 5.1.7 on 2025-10-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отправлено в архив'),
        ),
    ]
