# Generated by Django 5.1.7 on 2025-04-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='completed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
