# Generated by Django 5.1.7 on 2025-10-09 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_transaction_archived_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='archived_at',
        ),
    ]
