# Generated by Django 5.1.7 on 2026-02-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_remove_transaction_archived_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Сумма'),
        ),
    ]
