# Generated by Django 5.1.7 on 2025-04-01 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_transaction_completed_date_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.transactiontype', verbose_name='Тип операции'),
        ),
        migrations.AlterField(
            model_name='transactioncategory',
            name='type',
            field=models.CharField(choices=[('+', 'Приход'), ('-', 'Расход')], default='-', max_length=1, verbose_name='Знак (+/-)'),
        ),
    ]
