# Generated by Django 5.1.7 on 2025-04-01 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_transaction_type_alter_transactioncategory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.transactiontype', verbose_name='Тип операции'),
        ),
        migrations.AlterField(
            model_name='transactioncategory',
            name='type',
            field=models.CharField(choices=[('+', 'Приход'), ('-', 'Расход')], max_length=1, verbose_name='Знак (+/-)'),
        ),
    ]
