# Generated by Django 5.1.7 on 2026-04-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_alter_transaction_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyCapital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('capital', models.DecimalField(decimal_places=2, max_digits=20)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('year', 'month')},
            },
        ),
    ]
