# Generated by Django 5.1.7 on 2025-04-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_alter_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Приход'), ('expense', 'Расход'), ('order_payment', 'Оплата заказа'), ('transfer', 'Перевод между счетами')], max_length=255, verbose_name='Тип операции'),
        ),
    ]
