# Generated by Django 5.1.7 on 2025-04-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_alter_transactioncategory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncategory',
            name='type',
            field=models.CharField(choices=[('income', '+'), ('expense', '-')], max_length=255, verbose_name='Знак (+/-)'),
        ),
    ]
