# Generated by Django 5.1.7 on 2025-04-02 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_alter_transactioncategory_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionType',
        ),
    ]
