# Generated by Django 5.1.7 on 2025-04-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_delete_transactiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Баланс'),
        ),
    ]
