# Generated by Django 5.1.7 on 2025-04-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0012_alter_transaction_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='manager',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Приход'), ('expense', 'Расход'), ('order_payment', 'Оплата заказа'), ('transfer', 'Перевод между счетами'), ('client_account_deposit', 'Внос на ЛС клиента'), ('client_account_payment', 'Оплата с ЛС клиента')], max_length=255, verbose_name='Тип операции'),
        ),
    ]
