# Generated by Django 5.1.7 on 2025-04-13 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0013_remove_transaction_manager_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='related_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_transaction', to='ledger.transaction', verbose_name='Связанная транзакция'),
        ),
    ]
