# Generated by Django 5.1.7 on 2025-06-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0015_transaction_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='report_date',
            field=models.DateField(blank=True, null=True, verbose_name='Месяц реализации'),
        ),
    ]
