# Generated by Django 5.1.7 on 2025-04-12 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_permission_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='menu_items',
        ),
    ]
