# Generated by Django 5.1.7 on 2025-04-12 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_menu_items_field"),
    ]

    operations = []
