# Generated by Django 5.1.7 on 2025-04-12 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menuitem_options_remove_menuitem_category_and_more'),
        ('users', '0004_existing_usertypemenuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='menu_items',
            field=models.ManyToManyField(blank=True, related_name='user_types', to='menu.menuitem', verbose_name='Пункты меню'),
        ),
        migrations.CreateModel(
            name='UserTypeMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Папка в меню')),
                ('category_slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug категории')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menuitem')),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_menu_items', to='users.usertype')),
            ],
            options={
                'verbose_name': 'Связь типа пользователя с пунктом меню',
                'verbose_name_plural': 'Связи типов пользователей с пунктами меню',
                'ordering': ['order'],
                'unique_together': {('user_type', 'menu_item')},
            },
        ),
    ]
