# Generated by Django 5.1.7 on 2025-04-12 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usertype_menu_items_usertypemenuitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='menu_items',
        ),
    ]
