# Generated by Django 5.1.7 on 2025-12-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_files_as_cards',
            field=models.BooleanField(default=True, verbose_name='Отображать файлы в виде карточек'),
        ),
    ]
