# Generated by Django 5.1.7 on 2025-04-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menuitem_options_remove_menuitem_category_and_more'),
        ('users', '0006_remove_usertype_menu_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='menu_items',
            field=models.ManyToManyField(through='users.UserTypeMenuItem', to='menu.menuitem', verbose_name='Пункты меню'),
        ),
    ]
