# Generated by Django 5.1.7 on 2026-03-04 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menucategory_name'),
        ('users', '0008_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertypemenuitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menucategory'),
        ),
    ]
