# Generated by Django 5.1.7 on 2026-01-22 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SipuniIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sipuni_key', models.CharField(max_length=100, verbose_name='API ключ SIPUNI')),
                ('sipuni_user_number', models.CharField(max_length=20, verbose_name='Номер в системе SIPUNI')),
                ('internal_number', models.CharField(max_length=10, verbose_name='Внутренний номер менеджера')),
                ('manager_phone', models.CharField(help_text='На этот номер будет звонить SIPUNI', max_length=20, verbose_name='Телефон менеджера')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SipuniAccount',
        ),
    ]
