# Generated by Django 5.1.7 on 2026-01-22 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_sipuniintegration_delete_sipuniaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sipuniintegration',
            name='user',
        ),
        migrations.DeleteModel(
            name='ClientApi',
        ),
        migrations.DeleteModel(
            name='SipuniIntegration',
        ),
    ]
