# Generated by Django 5.1.7 on 2026-02-18 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='session',
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Сообщение чата', 'verbose_name_plural': 'Сообщения чата'},
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='role',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_processed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Обработано'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение пользователя'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ системы'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='response_html',
            field=models.TextField(blank=True, null=True, verbose_name='HTML ответ (таблицы)'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
    ]
