# Generated by Django 5.1.7 on 2026-02-18 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chatmessage_session_alter_chatmessage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('delete', 'Удаление'), ('query', 'Запрос данных')], max_length=20, verbose_name='Действие')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('object_repr', models.CharField(help_text="Например: 'Счет 4' или 'Транзакция №10'", max_length=255, verbose_name='Представление объекта')),
                ('query_text', models.TextField(verbose_name='Запрос пользователя')),
                ('data_before', models.JSONField(blank=True, help_text='Состояние объекта до изменения', null=True, verbose_name='Данные до')),
                ('data_after', models.JSONField(blank=True, help_text='Состояние объекта после изменения', null=True, verbose_name='Данные после')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('can_restore', models.BooleanField(default=False, verbose_name='Можно восстановить')),
                ('restored', models.BooleanField(default=False, verbose_name='Восстановлено')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата восстановления')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Ошибка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_action_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог действия чата',
                'verbose_name_plural': 'Логи действий чата',
                'ordering': ['-created_at'],
            },
        ),
    ]
