from django.urls import path
from . import views

app_name = "commerce"

urlpatterns = [
    path("products/list/", views.product_list, name="product_list"),
	path("orders/", views.orders, name="orders"),
    path("orders/<int:pk>/debt/", views.order_debt, name="order_debt"),
    path("orders/ids/", views.order_ids, name="order_ids"),
	path("orders/statuses/", views.order_statuses, name="order_statuses"),
	path("orders/<int:pk>/", views.order_detail, name="order_detail"),
	path("orders/add/", views.order_create, name="order_add"),
	path("orders/edit/<int:pk>/", views.order_update, name="order_edit"),
	path("orders/delete/<int:pk>/", views.order_delete, name="order_delete"),
	path("works/", views.works, name="works"),
	path("product_orders/", views.product_orders, name="product_orders"),
    path("clients/", views.clients, name="clients"),
	path("clients/list/", views.client_list, name="client_list"),
	path("clients/list/paginate/", views.clients_paginate, name="clients_paginate"),
    path("clients/balances/", views.client_balances, name="client_balances"),
	path("clients/<int:pk>/", views.client_detail, name="client_detail"),
	path("clients/add/", views.client_create, name="client_add"),
	path("clients/edit/<int:pk>/", views.client_update, name="client_edit"),
	path("clients/delete/<int:pk>/", views.client_delete, name="client_delete"),
	path("clients/contacts/add/", views.contact_create, name="contact_add"),
	path("clients/contacts/edit/<int:pk>/", views.contact_update, name="contact_edit"),
	path("clients/contacts/delete/<int:pk>/", views.contact_delete, name="contact_delete"),
	path("clients/contacts/<int:pk>/", views.contact_detail, name="contact_detail"),
	path("products/", views.products, name="products"),
	path("products/<int:pk>/", views.product_detail, name="product_detail"),
	path("products/add/", views.product_create, name="product_add"),
	path("products/edit/<int:pk>/", views.product_update, name="product_edit"),
	path("products/delete/<int:pk>/", views.product_delete, name="product_delete"),
	path("orders/archive/", views.orders_archive, name="orders_archive"),
	path("documents/types/", views.document_types, name="document_types"),
	path("documents/table/<int:pk>/", views.order_documents_table, name="order_documents_table"),
	path("documents/upload/", views.document_upload, name="document_upload"),
	path("clients/objects/<int:pk>/", views.client_object_detail, name="client_object_detail"),
	path("clients/objects/add/", views.client_object_create, name="client_object_add"),
	path("clients/objects/edit/<int:pk>/", views.client_object_update, name="client_object_edit"),
	path("clients/objects/delete/<int:pk>/", views.client_object_delete, name="client_object_delete"),
	path("orders/<int:pk>/viewers/", views.order_viewers, name="order_viewers"),
	path("orders/<int:pk>/remove_viewer/", views.order_remove_viewer, name="order_remove_viewer"),
	path("orders/<int:pk>/add_viewers/", views.order_add_viewers, name="order_add_viewers"),
	
	path("kanban/", views.kanban_board, name="kanban_board"),
    path("kanban/move/", views.kanban_move_client, name="kanban_move_client"),
	path("kanban/update_columns/", views.kanban_update_columns, name="kanban_update_columns"),
	path('kanban/quick_add_client/', views.kanban_quick_add_client, name='kanban_quick_add_client'),
	path('kanban/delete_column/<int:pk>/', views.kanban_delete_column, name='kanban_delete_column'),
	path("kanban/create_column/", views.kanban_create_column, name="kanban_create_column"),
]
